apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: abhi-pod
  namespace: web
spec:
  containers:
  - image: nginx
    name: nginx
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}