apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: helm-release-metrics-server
  namespace: flux-system
spec:
  chart:
    spec:
      chart: metrics-server
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: metrics-server
      version: 3.12.0
  interval: 10s
  targetNamespace: kube-system


apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: prometheus
spec:
  interval: 10m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 36.0.0
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
        namespace: prometheus
      interval: 5m